spring:
  application:
    name=study_backend
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://3dpit.synology.me:7432/postgres
    username: root
    password: root
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

    # url:jdbc:h2:mem:testdb
