spring:
  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
      dialect:
        org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true