version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
  redis_monitor:
    image: insready/redis-stat
    container_name: redis_monitor
    ports:
      - 63790:63790
    command: ["--server", "redis:6379"]
